// AArch64 Mach-O bootstrap.
//
// This file is linked with decoder.s and with the payload/model objects
// generated by the Mach-O packer.  The external labels below are intentionally
// data-driven so the packer can choose where the compressed bytes, runtime
// image metadata, and model state live.

.text
.align 2

.extern _arithmetic_decoder_init
.extern _arithmetic_decode_stream

.extern _websqz_compressed_start
.extern _websqz_compressed_end
.extern _websqz_decode_chunks_start
.extern _websqz_decode_chunks_end
.extern _websqz_prepare_image
.extern _websqz_launch_image

.globl _main
_main:
    stp     x29, x30, [sp, #-128]!
    mov     x29, sp
    stp     x19, x20, [sp, #16]
    stp     x21, x22, [sp, #32]
    stp     x23, x24, [sp, #48]
    stp     x25, x26, [sp, #64]
    mov     x21, x0                 // argc
    mov     x22, x1                 // argv
    mov     x23, x2                 // envp

    // ArithmeticDecoder context, matching decoder.s' 32-byte layout.
    adrp    x1, _websqz_compressed_start@PAGE
    add     x1, x1, _websqz_compressed_start@PAGEOFF
    adrp    x2, _websqz_compressed_end@PAGE
    add     x2, x2, _websqz_compressed_end@PAGEOFF
    sub     x2, x2, x1
    add     x20, sp, #96
    mov     x0, x20
    bl      _arithmetic_decoder_init

    bl      _websqz_prepare_image
    mov     x19, x0                 // mapped app image

    adrp    x24, _websqz_decode_chunks_start@PAGE
    add     x24, x24, _websqz_decode_chunks_start@PAGEOFF
    adrp    x25, _websqz_decode_chunks_end@PAGE
    add     x25, x25, _websqz_decode_chunks_end@PAGEOFF

1:
    cmp     x24, x25
    b.hs    2f

    ldr     x1, [x24], #8           // chunk image offset
    ldr     x2, [x24], #8           // chunk byte length
    add     x1, x19, x1
    mov     x0, x20
    bl      _arithmetic_decode_stream
    b       1b

2:
    mov     x0, x19
    mov     w1, w21
    mov     x2, x22
    mov     x3, x23
    bl      _websqz_launch_image

    ldp     x25, x26, [sp, #64]
    ldp     x23, x24, [sp, #48]
    ldp     x21, x22, [sp, #32]
    ldp     x19, x20, [sp, #16]
    ldp     x29, x30, [sp], #128
    ret
