// AArch64 Mach-O bootstrap.
//
// This file is linked with decoder.s and with the payload/model objects
// generated by the Mach-O packer.  The external labels below are intentionally
// data-driven so the packer can choose where the compressed bytes, decoded
// output, and model state live.

.text
.align 2

.extern _arithmetic_decoder_init
.extern _arithmetic_decode_stream

.extern _websqz_compressed_start
.extern _websqz_compressed_end
.extern _websqz_output_start
.extern _websqz_output_end
.extern _websqz_model_ctx
.extern _websqz_model_predict
.extern _websqz_model_learn
.extern _websqz_after_decode

.globl _main
_main:
    stp     x29, x30, [sp, #-80]!
    mov     x29, sp
    stp     x19, x20, [sp, #16]
    stp     x21, x22, [sp, #32]
    mov     x21, x0                 // argc
    mov     x22, x1                 // argv

    // ArithmeticDecoder context, matching decoder.s' 32-byte layout.
    adrp    x1, _websqz_compressed_start@PAGE
    add     x1, x1, _websqz_compressed_start@PAGEOFF
    adrp    x2, _websqz_compressed_end@PAGE
    add     x2, x2, _websqz_compressed_end@PAGEOFF
    sub     x2, x2, x1
    add     x0, sp, #48
    bl      _arithmetic_decoder_init

    add     x0, sp, #48
    adrp    x1, _websqz_output_start@PAGE
    add     x1, x1, _websqz_output_start@PAGEOFF
    adrp    x2, _websqz_output_end@PAGE
    add     x2, x2, _websqz_output_end@PAGEOFF
    sub     x2, x2, x1
    mov     x19, x1
    mov     x20, x2
    adrp    x3, _websqz_model_ctx@PAGE
    add     x3, x3, _websqz_model_ctx@PAGEOFF
    adrp    x4, _websqz_model_predict@PAGE
    add     x4, x4, _websqz_model_predict@PAGEOFF
    adrp    x5, _websqz_model_learn@PAGE
    add     x5, x5, _websqz_model_learn@PAGEOFF
    bl      _arithmetic_decode_stream

    mov     x0, x19
    mov     x1, x20
    mov     x2, x21
    mov     x3, x22
    bl      _websqz_after_decode

    ldp     x21, x22, [sp, #32]
    ldp     x19, x20, [sp, #16]
    ldp     x29, x30, [sp], #80
    mov     w0, #0
    ret
