[package]
name = "webcompressor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
bitflags = "2.9.1"
bytes = "1.10.1"
serde = { version="1.0.219", features=["derive"] }
serde_json = "1.0.140"
